version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_caddy: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: lazygram_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: lazygram_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  caddy:
    build:
      context: .
      dockerfile: ./compose/production/caddy/Dockerfile
    image: lazygram_production_caddy
    depends_on:
      - django
    volumes:
      - production_caddy:/root/.caddy
    env_file:
      - ./.envs/.production/.caddy
    ports:
      - "0.0.0.0:81:81"
      - "0.0.0.0:444:444"

  redis:
    image: redis:7.0-alpine

  celeryworker:
    <<: *django
    image: lazygram_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: lazygram_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: lazygram_production_flower
    ports:
      - "5556:5556"
    command: /start-flower
