version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_lazygram_react: {}
  production_caddy: {}


services:
  django_production: &django_production
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: lazygram_production_django
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    stdin_open: true
    tty: true

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: lazygram_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    ports:
      - 5432:5432

  # caddy:
  #   build:
  #     context: .
  #     dockerfile: ./compose/production/caddy/Dockerfile
  #   image: lazygram_production_caddy
  #   depends_on:
  #     - django
  #   volumes:
  #     - production_caddy:/root/.caddy
  #   env_file:
  #     - ./.envs/.production/.caddy
  #   ports:
  #     - "0.0.0.0:81:81"
  #     - "0.0.0.0:444:444"

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379

  celeryworker:
    <<: *django_production
    image: lazygram_production_celeryworker
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django_production
    image: lazygram_production_celerybeat
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django_production
    image: lazygram_production_flower
    ports:
      - "5556:5556"
    command: /start-flower

  react:
    build:
      context: ../lazygram_react
      dockerfile: ../lazygram_react/Dockerfile
    volumes:
      - production_lazygram_react:/lazygram_react/build

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./config/settings/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/settings/nginx/nginx-setup.conf:/etc/nginx/nginx.conf
      - production_lazygram_react:/var/www/build
    depends_on:
      - django_production
      - react