# Generated by Django 4.0.2 on 2022-10-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=255, verbose_name='Comment')),
                ('likes', models.PositiveIntegerField(blank=True, default=0, verbose_name='Likes of comments')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('commented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.profile', verbose_name='Commented by')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True)),
                ('picture', models.ImageField(null=True, upload_to='uploads/pictures_posted')),
                ('likes', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Likes')),
                ('description', models.CharField(blank=True, db_index=True, default='', max_length=250)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.profile')),
                ('profile_likedit', models.ManyToManyField(blank=True, help_text='Profiles that liked it a post.', null=True, related_name='liked_by', to='users.Profile', verbose_name='Liked it')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='ReplyComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(blank=True, default='', max_length=255, verbose_name='Comment replies')),
                ('like_reply', models.PositiveIntegerField(blank=True, default=0)),
                ('commentid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.comments')),
                ('replied_by', models.ManyToManyField(to='users.Profile', verbose_name='Replied by')),
            ],
            options={
                'verbose_name_plural': 'Replies',
            },
        ),
        migrations.CreateModel(
            name='PostSaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_id', to='users.profile', verbose_name='Profile ID')),
                ('saved_post', models.ManyToManyField(related_name='saved_posts', to='posts.Posts', verbose_name='Saved post')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post', to='posts.posts', verbose_name='Post'),
        ),
    ]
