#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


python3 /app/manage.py collectstatic --noinput
python3 /app/manage.py migrate

gunicorn --bind 0.0.0.0:8000 --chdir=/app config.wsgi:application
