#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python manage.py migrate
# python /app/manage.py flushexpiredtokens # Flushes any expired tokens in the outstanding token list
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5001 --chdir=/app