# Generated by Django 4.0.2 on 2022-12-25 00:48

from django.db import migrations, models
import django.db.models.deletion
import lazygram.applications.dm.models.dm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to=lazygram.applications.dm.models.dm.user_directory_path, verbose_name='Files')),
                ('viewed', models.BooleanField(default=False, verbose_name='Viewed')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('profile_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_from', to='users.profile', verbose_name='Profile')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to', to='users.profile', verbose_name='To profile')),
            ],
            options={
                'verbose_name_plural': 'Direct messages',
            },
        ),
    ]
